CREATE TABLE IF NOT EXISTS `Services` (
  `ServiceID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Price` DECIMAL(10,2) NOT NULL,
  `DataCap` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `Speed` VARCHAR(45) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ServiceID`)
) ENGINE = InnoDB;